INSERT INTO MEDICATION_PICKUP (PRESCRIPTION_ID,PATIENT_ID,PICKUP_DATE,PICKUP_STATUS)
SELECT ID,PATIENT_ID, case when to_char(current_date,'DY') in ('SAT') then TO_DATE(CURRENT_DATE)+2 else TO_DATE(CURRENT_DATE)+1 end AS PICKUP_DATE, 0 AS PICKUP_STATUS
from REPEAT_PRESCRIPTIONS
WHERE ID not in (select prescription_id from MEDICATION_PICKUP WHERE PICKUP_STATUS = 0)
AND (TO_DATE(CURRENT_DATE) -(TO_DATE(LAST_ISSUED_DATE) + ISSUE_DURATION_DAYS)) <=10
